"""init tables

Revision ID: 6a4e04b024cc
Revises: 
Create Date: 2025-10-19 18:15:43.886289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4e04b024cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('users', sa.Column('correo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ciudad', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pais', sa.String(), nullable=True))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('edad', sa.Integer(), nullable=True))
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_correo'), 'users', ['correo'], unique=True)
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_correo'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'edad')
    op.drop_column('users', 'direccion')
    op.drop_column('users', 'pais')
    op.drop_column('users', 'ciudad')
    op.drop_column('users', 'correo')
    op.drop_column('users', 'nombre')
    # ### end Alembic commands ###
